/**
 * Demo catalog imagery — locally generated brand renders.
 *
 * The demo catalog ships without real photography, so products are dressed
 * with the BodyScent render library in /public/images (generated by
 * `pnpm --filter @sugar-store/media-pipeline brand-art`): studio shots keyed
 * by the product's scent mood, plus a label macro and a dark editorial per
 * mood for PDP galleries. Selection is deterministic per seed, so a product
 * keeps the same imagery everywhere — and its bottle liquid always matches
 * the mood chip shown on cards and filters. Real images (R2 / Sanity URLs)
 * always take precedence — see `displayImage`.
 */
import { scentProfile } from './scent'

/** Scent-coloured liquid gradients [top, bottom] for the inline SVG fallback. */
const SCENTS: [string, string][] = [
  ['#F6B24A', '#C9692F'], // amber
  ['#E58AA6', '#B23A5E'], // rose
  ['#86CBA8', '#2E7D5B'], // green
  ['#83B6D8', '#2E6B8E'], // aqua
  ['#C3A2E0', '#7E4FB0'], // violet
  ['#E8C26A', '#B8902E'], // gold
  ['#E89B6A', '#B5571F'], // copper
  ['#6FBFB6', '#287F77'], // teal
]

function hash(seed: string): number {
  let h = 0
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0
  return h
}

/**
 * A coloured perfume-bottle illustration as an inline SVG data URI. Kept as
 * the load-error fallback (via `AppImage`'s `fallbackSrc`) since it can never
 * fail to load.
 */
export function bottleImage(seed: string): string {
  const h = hash(seed)
  const [c1, c2] = SCENTS[h % SCENTS.length]!
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 500'>
<defs>
<linearGradient id='bg' x1='0' y1='0' x2='0' y2='1'><stop offset='0' stop-color='#FBF5EE'/><stop offset='1' stop-color='#F1E2CF'/></linearGradient>
<linearGradient id='liq' x1='0' y1='0' x2='0' y2='1'><stop offset='0' stop-color='${c1}'/><stop offset='1' stop-color='${c2}'/></linearGradient>
</defs>
<rect width='400' height='500' fill='url(#bg)'/>
<ellipse cx='200' cy='432' rx='96' ry='16' fill='#1A1310' opacity='0.10'/>
<rect x='168' y='66' width='64' height='48' rx='10' fill='#241d1a'/>
<rect x='184' y='112' width='32' height='26' fill='${c2}' opacity='0.5'/>
<rect x='120' y='134' width='160' height='268' rx='28' fill='url(#liq)' stroke='#ffffff' stroke-opacity='0.45' stroke-width='2'/>
<rect x='142' y='156' width='20' height='200' rx='10' fill='#ffffff' opacity='0.2'/>
<rect x='156' y='212' width='88' height='86' rx='8' fill='#ffffff' opacity='0.92'/>
<circle cx='200' cy='236' r='11' fill='${c2}'/>
<rect x='170' y='258' width='60' height='6' rx='3' fill='${c2}' opacity='0.55'/>
</svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

/** True when a URL is missing or a seeded demo placeholder (not real media). */
export function isPlaceholder(url: string | null | undefined): boolean {
  return !url || url.includes('picsum.photos') || url.includes('loremflickr.com')
}

const SHAPE_COUNT = 4

/**
 * Studio render for a product — bottle shape varies by seed (+offset for
 * gallery variety) while the liquid colour always matches the product's
 * scent mood.
 */
export function productShot(seed: string, offset = 0): string {
  const mood = scentProfile(seed).mood.slug
  const variant = ((((hash(seed) >> 7) + offset) % SHAPE_COUNT) + SHAPE_COUNT) % SHAPE_COUNT
  return `/images/products/product-${mood}-${variant + 1}.webp`
}

/** PDP gallery: studio shot, label macro and dark editorial — one mood. */
export function productGallery(seed: string): string[] {
  const mood = scentProfile(seed).mood.slug
  return [
    productShot(seed),
    `/images/products/detail-${mood}.webp`,
    `/images/products/editorial-${mood}.webp`,
  ]
}

/** Real image when present, else the deterministic brand render. */
export function displayImage(
  url: string | null | undefined,
  seed: string,
  offset = 0,
): string {
  return isPlaceholder(url) ? productShot(seed, offset) : (url as string)
}
