import fs from 'node:fs'
import path from 'node:path'
import dotenv from 'dotenv'
import type { NextConfig } from 'next'

// Next.js only auto-loads .env files from this app's own directory, but the
// monorepo keeps a single source-of-truth .env at the repo root (the Medusa
// backend loads it the same way, via dotenv). Load that root .env here so the
// storefront picks up NEXT_PUBLIC_* values — most importantly the Medusa
// publishable key. Without it, Store API requests go out with no
// x-publishable-api-key header, Medusa answers 400, and every product list
// comes back empty ("No products found").
//
// dotenv is used here rather than @next/env's loadEnvConfig because Next.js
// already calls loadEnvConfig for this app's directory before evaluating
// next.config; @next/env caches that result and short-circuits any later call,
// so it would never read the root .env. dotenv has no such cache and, by
// default, does not override variables already present in process.env — so any
// app-level .env still wins.
function findRepoRoot(): string {
  let dir = process.cwd()
  while (path.dirname(dir) !== dir) {
    if (fs.existsSync(path.join(dir, 'pnpm-workspace.yaml'))) return dir
    dir = path.dirname(dir)
  }
  return process.cwd()
}
dotenv.config({ path: path.join(findRepoRoot(), '.env') })

interface Redirect {
  source: string
  destination: string
  permanent: boolean
}

/** Allow the configured media host (R2) for next/image, when set. */
function mediaPattern() {
  const base = process.env.NEXT_PUBLIC_MEDIA_BASE_URL
  if (!base) return []
  try {
    return [{ protocol: 'https' as const, hostname: new URL(base).hostname }]
  } catch {
    return []
  }
}

/**
 * Allow the Medusa backend's own host for next/image. Product photos uploaded
 * directly in the Admin (Thumbnail/Media) are stored by Medusa's local file
 * provider and served from this URL (e.g. http://localhost:9000/static/...)
 * rather than from R2 — without this pattern, next/image rejects them and
 * AppImage's onError swaps in the generated placeholder instead.
 */
function backendMediaPattern() {
  const base =
    process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL ?? process.env.MEDUSA_BACKEND_URL
  if (!base) return []
  try {
    const url = new URL(base)
    return [
      {
        protocol: url.protocol.replace(':', '') as 'http' | 'https',
        hostname: url.hostname,
        ...(url.port ? { port: url.port } : {}),
        pathname: '/static/**',
      },
    ]
  } catch {
    return []
  }
}

/** Load the Shopify→storefront redirect map generated by `pnpm redirects:build`. */
function loadRedirects(): Redirect[] {
  try {
    const raw = fs.readFileSync(
      path.join(process.cwd(), 'redirects.generated.json'),
      'utf8',
    )
    return JSON.parse(raw) as Redirect[]
  } catch {
    return []
  }
}

const config: NextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    // The demo catalog renders coloured perfume-bottle SVG data URIs as
    // placeholders (see lib/catalog/placeholder.ts). These are self-generated,
    // never user input, so allowing SVG is safe; the CSP keeps them inert.
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    remotePatterns: [
      { protocol: 'https', hostname: 'cdn.sanity.io' },
      { protocol: 'https', hostname: 'media.sugarcosmetics.com' },
      // Demo placeholder photo hosts (real product imagery replaces these).
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: 'loremflickr.com' },
      { protocol: 'https', hostname: '*.staticflickr.com' },
      ...mediaPattern(),
      ...backendMediaPattern(),
    ],
  },
  experimental: {
    optimizePackageImports: ['motion'],
  },
  async redirects() {
    return loadRedirects()
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
        ],
      },
    ]
  },
}

export default config
