import fs from 'node:fs'
import path from 'node:path'
import { loadEnvConfig } from '@next/env'
import type { NextConfig } from 'next'

// Next.js only auto-loads .env files from this app's own directory, but the
// monorepo keeps a single source-of-truth .env at the repo root (the Medusa
// backend loads it the same way). Load that root .env here so the storefront
// picks up NEXT_PUBLIC_* values — most importantly the Medusa publishable key.
// Without it, Store API requests go out with no x-publishable-api-key header,
// Medusa answers 400, and every product list comes back empty ("No products
// found"). Local app-level .env files still win, since loadEnvConfig does not
// overwrite variables already present in process.env.
function findRepoRoot(): string {
  let dir = process.cwd()
  while (path.dirname(dir) !== dir) {
    if (fs.existsSync(path.join(dir, 'pnpm-workspace.yaml'))) return dir
    dir = path.dirname(dir)
  }
  return process.cwd()
}
loadEnvConfig(findRepoRoot())

interface Redirect {
  source: string
  destination: string
  permanent: boolean
}

/** Allow the configured media host (R2) for next/image, when set. */
function mediaPattern() {
  const base = process.env.NEXT_PUBLIC_MEDIA_BASE_URL
  if (!base) return []
  try {
    return [{ protocol: 'https' as const, hostname: new URL(base).hostname }]
  } catch {
    return []
  }
}

/** Load the Shopify→storefront redirect map generated by `pnpm redirects:build`. */
function loadRedirects(): Redirect[] {
  try {
    const raw = fs.readFileSync(
      path.join(process.cwd(), 'redirects.generated.json'),
      'utf8',
    )
    return JSON.parse(raw) as Redirect[]
  } catch {
    return []
  }
}

const config: NextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      { protocol: 'https', hostname: 'cdn.sanity.io' },
      { protocol: 'https', hostname: 'media.sugarcosmetics.com' },
      // Placeholder host for the demo products seeded in apps/backend.
      { protocol: 'https', hostname: 'picsum.photos' },
      ...mediaPattern(),
    ],
  },
  experimental: {
    optimizePackageImports: ['motion'],
  },
  async redirects() {
    return loadRedirects()
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
        ],
      },
    ]
  },
}

export default config
